const project1btn=document.getElementById("project1");project1btn.addEventListener("dblclick",function(){window.open("https://newmicrob.github.io/Lab-7-JavaScript-Events/","_blank")});const project2btn=document.getElementById("project2");project2btn.addEventListener("dblclick",function(){window.open("https://newmicrob.github.io/accessible-registration/","_blank")});const project3btn=document.getElementById("project3");project3btn.addEventListener("dblclick",function(){window.open("https://newmicrob.github.io/Assignment-2-Build-a-Web-Page-Using-the-HTML5-Web-Storage-API/","_blank")});const project4btn=document.getElementById("project4");project4btn.addEventListener("dblclick",function(){window.open("https://newmicrob.github.io/Group-Recipe-Project/","_blank")});const projectDetails=document.getElementById("projectDetails");const buttons=[{id:"project1",content:"Details: For this assignement we were tasked with working with different type of events. They were mouse events, keyboard events, form events, focus and blur, and event delegation. Double click the button to be taken to the website."},{id:"project2",content:"Details: This was the first form I created. It has different options for form such as date(calender drop down), radio with a fieldset, as well as provinces drop down where we had to add options. Double click the button to be taken to the website."},{id:"project3",content:"Details: This assignment tasked us with updating the web storage and populating a part of the page that was empty before. It also has buttons to save the name and delete the input in the storage. Double click the button to be taken to the website."},{id:"project4",content:"Details: Our Assignement for this task was to work in a  group and create a dynamic website. We decided on a recipe cook book. I created and modified my first navbar for this project that links to other pages that store images for the different options. There is a preferences section where the user can click on one and it will save the choices, there will be a select all button that as the name states selects all of the choices, there is also a random button that has hover effects and a transfrom effect to make it look like its being pushed. Double click the button to be taken to the website."},];buttons.forEach(button=>{const btnElement=document.getElementById(button.id);btnElement.addEventListener("click",function(){projectDetails.innerHTML=`<p>${button.content}</p>`;projectDetails.classList.remove("hidden")})});window.addEventListener("load",function(){projectDetails.classList.add("hidden")});function validateForm(){alert("Validating form...");let fName=form.fName.value;let lName=form.lName.value;let email=form.email.value;let tel=form.tel.value;let honorifics=document.querySelectorAll('input[name="honorific"]:checked');if(honorifics.length===0){alert("Please select an honorific.");return!1}
if(fName===""||lName===""){alert("Please fill in the * fields");return!1}
if(email==""||!validateEmail(email)){alert("Please use standard email format i.e. example@email.com");return!1}
if(tel==""||!validatePhone(tel)){alert("Please enter phone number in the format i.e. 123-123-1234");return!1}
return!0}
function validateEmail(email){const re=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;return re.test(String(email).toLowerCase())}
function validatePhone(tel){const re=/^\d{3}-\d{3}-\d{4}$/;return re.test(String(tel))}
function openNav(){document.getElementById("navBar").style.width="250px"}
function closeNav(){document.getElementById("navBar").style.width="0"}
function toggleSwitch(){var element=document.body;element.classList.toggle("dark-mode")}